const WORKER_HEARTBEAT_KEY = "acis:worker:analytics:heartbeat";
const WORKER_HEARTBEAT_MAX_AGE_MS = Number(process.env.WORKER_HEARTBEAT_MAX_AGE_MS || 30000);
const WORKER_HEARTBEAT_INTERVAL_MS = Number(process.env.WORKER_HEARTBEAT_INTERVAL_MS || 10000);

module.exports = {
  WORKER_HEARTBEAT_KEY,
  WORKER_HEARTBEAT_MAX_AGE_MS,
  WORKER_HEARTBEAT_INTERVAL_MS,
};

